### PR TITLE
FEATURE - Module to look up local IP address and live IP Address.

### PR DESCRIPTION
**Pull request by anishsujanani**
For the live IP Address: A request is sent to whatsmyip.com, BeautifulSoup is used to extract the live IP Address.
For the local/private IP: A socket connection is initialised to Google DNS servers, getsockname() is used to get the machine's current private IP.

These tools might be helpful as quick lookups while working on other projects, or could be used along with other projects when IP Addresses dynamically change.

### CODE REVIEW

**Comment by ashwini0529** [comment]
Hey, that's amazing! Can you please update the readme as well to let users know about the feature?

**Comment by anishsujanani** [comment]
Will do, I'll put in another commit in a couple of hours or so :)

**Comment by anishsujanani** [comment]
@ashwini0529 I've updated requirements, added the module to __init__ and updated the README.

**Comment by ashwini0529** [comment]
Thank you @asi7296 for your contribution! 😄 🎉

**Pull request merged**
