### PR TITLE
File for plotting Graphs has been added

### PR DESCRIPTION
**Pull request by Shubhamsharma09**

### CODE REVIEW

**Comment by shubhodeep9** [comment]
@Shubhamsharma09 add the requirements for installation

**Comment by shubhodeep9** [comment]
@Shubhamsharma09 rest seems fine to me.
Do the needed, and lets merge your PR

**Comment by Shubhamsharma09** [comment]
I didn't get that, what requirements. I think I have added all the requirements.

**Comment by shubhodeep9** [comment]
@Shubhamsharma09 Hi I see you have not updated the `requirements.py` file. 
Kindly go through it.

**Comment by Shubhamsharma09** [comment]
I am a bit confused, I have to add some details about it in requirements.txt file

**Comment by shubhodeep9** [comment]
@Shubhamsharma09 see, in requirements file you put the libraries used with the version used.
So just add a commit consisting of the file with the libraries used by you in your task.

**Comment by Shubhamsharma09** [comment]
ok @shubhodeep9

**Comment by Shubhamsharma09** [comment]
@shubhodeep9 modification has been done!

**Comment by shubhodeep9** [comment]
@Shubhamsharma09 seems good
I will merge it now.
Happy hacking

**Comment by Shubhamsharma09** [comment]
@shubhodeep9 is there any other project on which I can work upon.

**Comment by shubhodeep9** [comment]
@Shubhamsharma09 go through [my profile](https://github.com/shubhodeep9) and [ashwini's profile](https://github.com/ashwini0529).

**Pull request merged**
