### PR TITLE
[WIP]Adding image scraping

### PR DESCRIPTION
**Pull request by ba11b0y**
Adds to #18 
I know it is violating the do not repeat yourself(DRY) principle, as I am not clear how should I include this addition. 
@ashwini0529 If you could tell me if this is fine or should I improve upon the structure.

### CODE REVIEW

**Review by ashwini0529 — APPROVED** [review]

**Comment by ashwini0529** [comment]
Included in `requirements.txt`?

**Comment by ba11b0y** [comment]
@ashwini0529 I have updated the requirements as well as the usage. Please let me know if any corrections are needed.
Also I was thinking of defining a function outside the scope of the `scrape` function, to eliminate repetition of the code for scraping images.
Since that would be a major change to the code style, your thoughts?

**Comment by ashwini0529** [comment]
Hey @invinciblycool I guess that would be better. 😄  Please go ahead with it! 🎉

**Comment by ba11b0y** [comment]
@ashwini0529 I accidentally squashed the wrong number of commits. What should I do now? :worried: 
Closing the PR can be a solution, but is there any way out without closing the PR.

**Comment by ba11b0y** [comment]
@ashwini0529 Then should I open a new PR, and close this.
Sorry again for the mess. :worried: 
I guess I need to go through squashing commits once again.

**Comment by ashwini0529** [comment]
Haha Alright! You could fix it in this PR but if you think that opening a new PR would be easy as of now, go ahead! 👍

**Comment by ba11b0y** [comment]
Done.
@ashwini0529 Intentionally kept the three commits instead of squashing them into one.

**Review by ashwini0529 — APPROVED** [review]

**Pull request merged**
