### PR TITLE
Restructuring generator

### PR DESCRIPTION
**Pull request by willBoyd8**
To avoid lumping **all** of `faker`'s functionality into one file, `generator` could be restructured. This adds complexity, but:

1. Still lets people put functionality in `faker.generator.<your function here>()` using `hackr/generator/__init__.py`
2. Lets people group new functionality into files (`faker.generator.file_name.function()`) by putting `function` within `hackr/generator/file_name` and adding `from .file_name import *` to `hackr/generator/file_name`

It also refactors `hackr/__init__.py` to make the end modification play nicely with python 2 and 3 and adds a `Documentation` directory describing how to add new items to generator and how to use `internet`

### CODE REVIEW

**Comment by ashwini0529** [comment]
Hey @willBoyd8 Great work! Can you please check the updated code and rebase?

**Comment by willBoyd8** [comment]
I'm not quite sure I understand `check the updated code and rebase` - this is a little new. If there are any changes required, I can do them later tonight.

**Comment by ashwini0529** [comment]
Yeah so basically the updated code has few changes in `generator.py` causing conflicts. So can you please restructure it and update? 😄

**Comment by willBoyd8** [comment]
Ok. Updated the `hackr.generator.dates()` function and the `hackr/__init__.py` from the pytorn source (although I don't know why it shows the old `willboyd8/hackr/__init__.py` as being replaced...). The only other conflict is the move of `hackr/generator.py` to `hackr/generator/__init__.py`. (As `generator.py` is deleted in the move)

**Comment by ashwini0529** [comment]
@willBoyd8 conflicts. :/

**Pull request closed without merging**
