### PR TITLE
JSON base64 Image Store

### PR DESCRIPTION
**Pull request by akshitgrover**
Images are encoded and base64 data is kept in JSON file against a key (unique), image extensions are also stored to avoid extension conflict when an image is decoded. #16

### CODE REVIEW

**Comment by ashwini0529** [comment]
Hey @akshitgrover requirements file needs to be updated. 😄

**Comment by akshitgrover** [comment]
But all these modules are inbuilt.

**Comment by ashwini0529** [comment]
Image?

**Comment by akshitgrover** [comment]
No image module is used.

**Comment by shubhodeep9** [comment]
@ashwini0529 `image` is his module.

**Comment by akshitgrover** [comment]
I just put the file name of image.py in __init__.py there is no use of that right?
should i remove it?

**Comment by shubhodeep9** [comment]
@akshitgrover its fine.

**Comment by ashwini0529** [comment]
@akshitgrover can you please squash your commit into one?

**Comment by shubhodeep9** [comment]
@akshitgrover no need, I will take care of it. Great job!

**Pull request merged**
